# table schema queries
CREATE DATABASE IF NOT EXISTS `sample_store`;

USE `sample_store`;

CREATE TABLE IF NOT EXISTS `users` (
	`IdUser` INT(11) NOT NULL AUTO_INCREMENT,
	`Username` VARCHAR(50) NOT NULL DEFAULT '',
	`Email` VARCHAR(50) NOT NULL DEFAULT '',
	`Password` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'SHA-1 algorithm.',
	PRIMARY KEY (`IdUser`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `products` (
	`IdProduct` INT(11) NOT NULL AUTO_INCREMENT,
	`ProductName` VARCHAR(30) NOT NULL DEFAULT '',
	`Price` INT(5) NOT NULL,
	`Currency` VARCHAR(3) NOT NULL DEFAULT 'RON',
	PRIMARY KEY (`IdProduct`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `orders` (
	`IdOrder` INT(11) NOT NULL AUTO_INCREMENT,
	`Date` timestamp NULL,
	`IdUser` INT(11) NOT NULL,
	`IdProduct` INT(11) NOT NULL,
	PRIMARY KEY (`IdOrder`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;

CREATE TABLE IF NOT EXISTS `user_credentials` (
	`IdUserCredentials` INT(11) NOT NULL AUTO_INCREMENT,
	`ClientId` VARCHAR(50) NOT NULL DEFAULT '',
	`SecretKey` VARCHAR(50) NOT NULL DEFAULT '',
	`Email` VARCHAR(50) NOT NULL DEFAULT '',
	`AddDate`DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`IdUserCredentials`)
)
	COLLATE='utf8_general_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=0;
